version: 2.1

orbs:
  # Always take the latest version of the orb, this allows us to
  # run specs against Solidus supported versions only without the need
  # to change this configuration every time a Solidus version is released
  # or goes EOL.
  solidusio_extensions: solidusio/extensions@volatile

jobs:
  run-specs-with-postgres:
    executor: solidusio_extensions/postgres
    steps:
      - solidusio_extensions/run-tests
  run-specs-with-mysql:
    executor: solidusio_extensions/mysql
    steps:
      - solidusio_extensions/run-tests
  lint-code:
    executor: solidusio_extensions/sqlite-memory
    steps:
      - checkout
      - run:
          name: 'Solidus master: Generate Gemfile.lock'
          command: bundle lock
          environment:
            SOLIDUS_BRANCH: master
          when: always
      - restore_cache:
          name: 'Solidus master: Restore Bundler cache'
          keys:
            - gems-v3-ruby-v2-5-6-solidus-master-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gems-v3-ruby-v2-5-6-solidus-master-
          when: always
      - run:
          name: 'Solidus master:  Install gems'
          command: bundle install --path=vendor/bundle
          environment:
            SOLIDUS_BRANCH: master
          when: always
      - save_cache:
          name: 'Solidus master: Save Bundler cache'
          key: gems-v3-ruby-v2-5-6-solidus-master-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
          when: always
      - run:
          name: 'Runs RuboCop on Solidus master'
          command: bundle exec rubocop -ESP
          environment:
            SOLIDUS_BRANCH: master
            TEST_RESULTS_PATH: test-results/gems-v3-ruby-v2-5-6-solidus-master/results.xml
          when: always

workflows:
  "Run specs on supported Solidus versions":
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
      - lint-code

  "Weekly run specs against master":
    triggers:
      - schedule:
          cron: "0 0 * * 4" # every Thursday
          filters:
            branches:
              only:
                - master
    jobs:
      - run-specs-with-postgres
      - run-specs-with-mysql
